{% set version = '0.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dt
  version: {{ version|replace("-", "_") }}

source:
  fn: DT_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/DT_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/DT/DT_{{ version }}.tar.gz
  sha256: 3daa96b819ca54e5fbc2c7d78cb3637982a2d44be58cea0683663b71cfc7fa19

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: jsonlite (>= 0.9.16), knitr (>= 1.8), rmarkdown, shiny (>= 0.12.1)
requirements:
  build:

  host:
    - r-base
    - r-crosstalk
    - r-htmltools >=0.3.6
    - r-htmlwidgets >=1.0
    - r-magrittr

  run:
    - r-base
    - r-crosstalk
    - r-htmltools >=0.3.6
    - r-htmlwidgets >=1.0
    - r-magrittr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('DT')"           # [not win]
    - "\"%R%\" -e \"library('DT')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://rstudio.github.io/DT
  license: GPL-3 | file LICENSE
  summary: Data objects in R can be rendered as HTML tables using the JavaScript library 'DataTables'
    (typically via R Markdown or Shiny). The 'DataTables' library has been included
    in this R package. The package name 'DT' is an abbreviation of 'DataTables'.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: DT
# Type: Package
# Title: A Wrapper of the JavaScript Library 'DataTables'
# Version: 0.4
# Authors@R: c( person("Yihui", "Xie", email = "xie@yihui.name", role = c("aut", "cre")), person("Joe", "Cheng", role = "ctb"), person("JJ", "Allaire", role = "ctb"), person("Xianying", "Tan", role = "ctb"), person("Maximilian", "Girlich", role = "ctb"), person("jQuery contributors", role = c("ctb", "cph"), comment = "jQuery in htmlwidgets/lib"), person("SpryMedia Limited", role = c("ctb", "cph"), comment = "DataTables in htmlwidgets/lib"), person("Brian", "Reavis", role = c("ctb", "cph"), comment = "selectize.js in htmlwidgets/lib"), person("Leon", "Gersen", role = c("ctb", "cph"), comment = "noUiSlider in htmlwidgets/lib"), person("Bartek", "Szopka", role = c("ctb", "cph"), comment = "jquery.highlight.js in htmlwidgets/lib"), person("RStudio Inc", role = "cph") )
# Maintainer: Yihui Xie <xie@yihui.name>
# Description: Data objects in R can be rendered as HTML tables using the JavaScript library 'DataTables' (typically via R Markdown or Shiny). The 'DataTables' library has been included in this R package. The package name 'DT' is an abbreviation of 'DataTables'.
# URL: https://rstudio.github.io/DT
# BugReports: https://github.com/rstudio/DT/issues
# License: GPL-3 | file LICENSE
# Imports: htmltools (>= 0.3.6), htmlwidgets (>= 1.0), magrittr, crosstalk
# Suggests: jsonlite (>= 0.9.16), knitr (>= 1.8), rmarkdown, shiny (>= 0.12.1)
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-01-30 21:06:51 UTC; yihui
# Author: Yihui Xie [aut, cre], Joe Cheng [ctb], JJ Allaire [ctb], Xianying Tan [ctb], Maximilian Girlich [ctb], jQuery contributors [ctb, cph] (jQuery in htmlwidgets/lib), SpryMedia Limited [ctb, cph] (DataTables in htmlwidgets/lib), Brian Reavis [ctb, cph] (selectize.js in htmlwidgets/lib), Leon Gersen [ctb, cph] (noUiSlider in htmlwidgets/lib), Bartek Szopka [ctb, cph] (jquery.highlight.js in htmlwidgets/lib), RStudio Inc [cph]
# Repository: CRAN
# Date/Publication: 2018-01-30 22:54:05 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
