travis:
  secure:
    BINSTAR_TOKEN: rmBMRN1CGHHH0iNS1ucoPQE8MHKfGntStJBS11fsZL/B6Mqc6WSFEDDVUbpKokJjbJ/Dj6W1GJTKDtJvRqrn4bF8YBoOqZKUozaAdjFxxt9iPGCzBkoraIm4sORiQUtv/VFNxKzkMkJFWFbg2P6mtxHdZGCAGYjjMDIzkKrRSJN0zACD74NMB+m6FMSmb8lPKZSF/7mV15oa4DIfzrKnSx/gRUbvLGrGuJCcdpbhAWHfHoree7uD1CUn8s8mA52y9bm1SHPZYj495HxyXCkAPAJBJRSYG1xlkWE2tVIFOEFm0IBCE6WE4cqAao+iauSXkZaaS6B3IH2jXt3JMv3dMuTVko+5RugwmEQihcxd7hbUMpJbo1tQ+ilYWWFvypY7LbNkCZy42cR66fs++7oEMi/A9lSldt6J2J7AENdWJVW5eUnolCh3N9Ob2QNHjvB50pRpCyRcLioy7wnSnqSWK7Gm+Bv9/d3ywcidimN9Ohk19ISUbqz5q5lTSDNpybMNjuKpqAFYKkNXF7FoJunyFGSb/C4EEFRTa36r2u2/R9BuxhDRfuRDcsXHmYXvZi4lg3ER6yrf3sdoy8jEqi3nABRXzoIiGkeDDoeYJbC//p0ajYp8GSQ6a72YzGMEitzxFv/CnAZpRj4Xrq/YHJM9Z1U36x2CnBqyXj+w9RFtBjQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
