travis:
  secure:
    BINSTAR_TOKEN: OjsdaX3OmEJb3Vz1rTlLwTKRk2nMrJmpRuQrWwl7G9ulGd+IbzXdo9H58F9ffnran3ZMj4O82dKzHvvvDyy4QnzCZwhz/hMerUnIKuMGS90uezv6Wd7OzqAZSdO5SShEFm1fuC8zZsBK8KIRSU04tBwoq8Lr4a172FaAtgUSAgl6gagtEzsdmgF5ppmCkq7aSjiNTtWAPOU8fKJH2Vjo099/YQCiVLKWEpl/sIrr5YBloPWvBbMtaaHEIeiCEZHmZHAqbgdUKQQBxApVp9L3eZq14cNf83hr0N46hWw1OOo49Q6S1EkFSzKoyiO7UStZE+HYgSyVQNCAN/Fy55bffWnJpLOq8Q7OKMZaiAju5nMLQe36MnC9vrozfrbQFzKT+3GGb9HCQ449GxiZPvacF9vskEuenhuREJt87hoUFOdI6s2ln9GlJpPI3KCTq4fZ8JWMnuxt1uj3NapQG3ZdA7y7h1fY9lb8mPJ2szq/QHZcVeAxecobOp/x/Py6qrWkl3Oy5s6Y7ESLyb7myUzMTT4WKJ0MGiCjxTO15rg6xnTFVfAYSWbTIv9zqxLWg/J3muRKZTF/Ly6oDFy8IG1sRZs3s44sC/uAmb+KzQbual0vgDRC1kFO8TuNad8h+vu03XaX7pg4sZHEANs8aRTsLZyXvpjt89hLPYHPKkd129k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
